### PR TITLE
Fix MinGW builds

### LINKED ISSUE #57: MXE/MinGW builds currently fail
From https://github.com/3MFConsortium/lib3mf/pull/44 :

It [The configuration] picks the wrong path for MXE/MinGW builds with if (UNIX). Changing that to if (UNIX OR MINGW) should solve that. Or maybe switching the conditions and use WIN32?

### PR DESCRIPTION
**Pull request by qmuntal**
This pull request fixes two issues in the MinGW toolchain:

1. The CMake config required the uuid library when using UNIX and MINGW compilers but the NMR::CUUID class is including objbase.h, implemented in the ole32.dll. With the changes in this pull request when MINGW and WIN32 are defined the ole32 implementation will be used, else the uuid.h. This fixes #57.

2.  The file _VersionResource.rc_ was including winres.h, which is an MFC header not included in the MinGW distro, thus making the compilation of the lib3MF.dll fail. As the file does not depends on MFC code but generic Platform SDK, the winresrc.h header should be used instead, which is indeed included in the MinGW distro. This helps #78.

Both changes have been tested with Visual Studio 15 2017 and MinGW in Windows.

Edit: Adding a MinGW-w64 build to Travis CI pipeline to test that MinGW toolchain works in Linux.

### CODE REVIEW

**Comment by t-paul** [comment]
Why is OLE32 needed in addition, building on MXE/MinGW works for me by just removing the guards for not using the Windows implementation (and making `objbase.h` all lowercase).

See https://github.com/openscad/mxe/blob/openscad-snapshot-build/src/lib3mf-1-uuid.patch

**Comment by qmuntal** [comment]
@t-paul is right, ole32 is not needed, only the WIN32 guard.

**Comment by qmuntal** [comment]
Glad to help!

The GenerateMinGW.sh is intended to be executed from a Linux instance. To compile from Windows you need to run `cmake .. -G ¨MinGW Makefiles¨` from build directory. I haven't added a .bat as it is not possible to execute MinGW together with Windows in Travis (Windows is not supported), so there is no need to call it at the moment.

If you still have problems with the compiler I would uninstall the winbuilds and install directly MinGW from [Sourceforge](https://sourceforge.net/projects/mingw-w64/). In the installer choose the following options: x86_64-8.1.0-posix-seh. Another easier way is to use [Chocolatey](https://chocolatey.org/) and run `choco install mingw`.

**Comment by martinweismann** [comment]
Thanks for clarifying this!

My mistake was
- calling
```cmake .. -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake -G "MinGW Makefiles```
with the toolchain-file set up by `GenerateMinGW.sh`
- instead of simply running
```cmake .. -G "MinGW Makefiles"```

With that, I was able to verify the Windows MinGW build now, too.
Cheers!

**Pull request merged**
