### PR TITLE
Secure Content Spec Implementation

### PR DESCRIPTION
**Pull request by feliperoos**
Hi @martinweismann 

This is a preliminary work from the secure content implementation, which still misses ~~the encryption file format and~~ some minor fixes that I'll continue to work on. Hopefully it's building properly and unlocks your work of preparing the new release. Let me know if you have any questions.

I've included this on top of your RefactorPackageID branch from this repo. Tests are running fine.

### CODE REVIEW

**Comment by feliperoos** [comment]
@martinweismann I've just added support for the encrypted file header.

**Comment by feliperoos** [comment]
@martinweismann These are the points I've collected. Let me know if I've missed anything.
- [ ] Add a proper return value field to the callbacks
- [ ] Update CKeyStoreResourceData to replace string path by a PPackageModelPath
- [ ] Implement default random number generator callback using std:: implementation
- [ ] Refactor CModelReaderWarning into CModelWarning
- [ ] Add warning mechanism to Writer and advice when using the local RNG call
- [ ] Writer to implement access methods to set warning level (strict mode)
- [ ] Add example to SDK with proper encrypted file, code to throw implementation on encryption parts and point to UnitTest_EncryptionUtils (to avoid binding to libressl)
- [ ] Make sure CResource::SetPackagePart and CPackagePart::SetPath are working as expected with a new test
- [ ] Memory leak investigation

**Comment by feliperoos** [comment]
@martinweismann I've notice calling SetPackagePart on a resource before it gets added to a build item does not work, not sure whether that is expected.
I have added an example of how to construct secure content based on the cube example. Let me know if you think we should include a reading example as well.

**Comment by martinweismann** [comment]
> @martinweismann I've notice calling SetPackagePart on a resource before it gets added to a build item does not work, not sure whether that is expected.
No, this should work. I am adding a top level checkbox su woe do not forget.

> I have added an example of how to construct secure content based on the cube example. Let me know if you think we should include a reading example as well.
Yes, we should also have a reading example.

**Pull request merged**
